// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: proto/bgpwatch.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BGPWatch_GetTotals_FullMethodName                   = "/bgpwatch.BGPWatch/GetTotals"
	BGPWatch_GetMasks_FullMethodName                    = "/bgpwatch.BGPWatch/GetMasks"
	BGPWatch_GetSystemStats_FullMethodName              = "/bgpwatch.BGPWatch/GetSystemStats"
	BGPWatch_GetRoute_FullMethodName                    = "/bgpwatch.BGPWatch/GetRoute"
	BGPWatch_GetRoutes_FullMethodName                   = "/bgpwatch.BGPWatch/GetRoutes"
	BGPWatch_GetPrefixesByOrigin_FullMethodName         = "/bgpwatch.BGPWatch/GetPrefixesByOrigin"
	BGPWatch_GetRoutesByOrigin_FullMethodName           = "/bgpwatch.BGPWatch/GetRoutesByOrigin"
	BGPWatch_GetPrefixesByAsPath_FullMethodName         = "/bgpwatch.BGPWatch/GetPrefixesByAsPath"
	BGPWatch_GetPrefixesByCommunity_FullMethodName      = "/bgpwatch.BGPWatch/GetPrefixesByCommunity"
	BGPWatch_GetPrefixesByLargeCommunity_FullMethodName = "/bgpwatch.BGPWatch/GetPrefixesByLargeCommunity"
	BGPWatch_GetInvalidPrefixes_FullMethodName          = "/bgpwatch.BGPWatch/GetInvalidPrefixes"
)

// BGPWatchClient is the client API for BGPWatch service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BGPWatchClient interface {
	// GetTotals returns the total number of IPv4 and IPv6 prefixes across all peers.
	GetTotals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TotalsResponse, error)
	// GetMasks returns the subnet mask distributions for IPv4 and IPv6.
	GetMasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MasksResponse, error)
	// GetSystemStats returns memory usage statistics for the system and per peer.
	GetSystemStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemStatsResponse, error)
	// GetRoute looks up a route by IP address (LPM) or CIDR prefix (exact match).
	GetRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteLookupResponse, error)
	// GetRoutes looks up a route across all peers.
	GetRoutes(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RoutesResponse, error)
	// GetPrefixesByOrigin returns all IPv4 and IPv6 prefixes originated by the given ASN (lightweight).
	GetPrefixesByOrigin(ctx context.Context, in *OriginRequest, opts ...grpc.CallOption) (*PrefixesResponse, error)
	// GetRoutesByOrigin returns all IPv4 and IPv6 routes originated by the given ASN (detailed).
	GetRoutesByOrigin(ctx context.Context, in *OriginRequest, opts ...grpc.CallOption) (*RoutesResponse, error)
	// GetPrefixesByAsPath returns all IPv4 and IPv6 prefixes matching the given AS path regex.
	GetPrefixesByAsPath(ctx context.Context, in *AsPathRequest, opts ...grpc.CallOption) (*RoutesResponse, error)
	// GetPrefixesByCommunity returns all IPv4 and IPv6 routes matching the given community.
	GetPrefixesByCommunity(ctx context.Context, in *CommunityRequest, opts ...grpc.CallOption) (*RoutesResponse, error)
	// GetPrefixesByLargeCommunity returns all IPv4 and IPv6 routes matching the given large community.
	GetPrefixesByLargeCommunity(ctx context.Context, in *LargeCommunityRequest, opts ...grpc.CallOption) (*RoutesResponse, error)
	// GetInvalidPrefixes returns all IPv4 and IPv6 prefixes with local_pref = 50 (lightweight).
	GetInvalidPrefixes(ctx context.Context, in *OriginRequest, opts ...grpc.CallOption) (*PrefixesResponse, error)
}

type bGPWatchClient struct {
	cc grpc.ClientConnInterface
}

func NewBGPWatchClient(cc grpc.ClientConnInterface) BGPWatchClient {
	return &bGPWatchClient{cc}
}

func (c *bGPWatchClient) GetTotals(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*TotalsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TotalsResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetTotals_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPWatchClient) GetMasks(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*MasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MasksResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetMasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPWatchClient) GetSystemStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*SystemStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SystemStatsResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetSystemStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPWatchClient) GetRoute(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RouteLookupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RouteLookupResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetRoute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPWatchClient) GetRoutes(ctx context.Context, in *RouteRequest, opts ...grpc.CallOption) (*RoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetRoutes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPWatchClient) GetPrefixesByOrigin(ctx context.Context, in *OriginRequest, opts ...grpc.CallOption) (*PrefixesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrefixesResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetPrefixesByOrigin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPWatchClient) GetRoutesByOrigin(ctx context.Context, in *OriginRequest, opts ...grpc.CallOption) (*RoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetRoutesByOrigin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPWatchClient) GetPrefixesByAsPath(ctx context.Context, in *AsPathRequest, opts ...grpc.CallOption) (*RoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetPrefixesByAsPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPWatchClient) GetPrefixesByCommunity(ctx context.Context, in *CommunityRequest, opts ...grpc.CallOption) (*RoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetPrefixesByCommunity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPWatchClient) GetPrefixesByLargeCommunity(ctx context.Context, in *LargeCommunityRequest, opts ...grpc.CallOption) (*RoutesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutesResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetPrefixesByLargeCommunity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bGPWatchClient) GetInvalidPrefixes(ctx context.Context, in *OriginRequest, opts ...grpc.CallOption) (*PrefixesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrefixesResponse)
	err := c.cc.Invoke(ctx, BGPWatch_GetInvalidPrefixes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BGPWatchServer is the server API for BGPWatch service.
// All implementations must embed UnimplementedBGPWatchServer
// for forward compatibility.
type BGPWatchServer interface {
	// GetTotals returns the total number of IPv4 and IPv6 prefixes across all peers.
	GetTotals(context.Context, *Empty) (*TotalsResponse, error)
	// GetMasks returns the subnet mask distributions for IPv4 and IPv6.
	GetMasks(context.Context, *Empty) (*MasksResponse, error)
	// GetSystemStats returns memory usage statistics for the system and per peer.
	GetSystemStats(context.Context, *Empty) (*SystemStatsResponse, error)
	// GetRoute looks up a route by IP address (LPM) or CIDR prefix (exact match).
	GetRoute(context.Context, *RouteRequest) (*RouteLookupResponse, error)
	// GetRoutes looks up a route across all peers.
	GetRoutes(context.Context, *RouteRequest) (*RoutesResponse, error)
	// GetPrefixesByOrigin returns all IPv4 and IPv6 prefixes originated by the given ASN (lightweight).
	GetPrefixesByOrigin(context.Context, *OriginRequest) (*PrefixesResponse, error)
	// GetRoutesByOrigin returns all IPv4 and IPv6 routes originated by the given ASN (detailed).
	GetRoutesByOrigin(context.Context, *OriginRequest) (*RoutesResponse, error)
	// GetPrefixesByAsPath returns all IPv4 and IPv6 prefixes matching the given AS path regex.
	GetPrefixesByAsPath(context.Context, *AsPathRequest) (*RoutesResponse, error)
	// GetPrefixesByCommunity returns all IPv4 and IPv6 routes matching the given community.
	GetPrefixesByCommunity(context.Context, *CommunityRequest) (*RoutesResponse, error)
	// GetPrefixesByLargeCommunity returns all IPv4 and IPv6 routes matching the given large community.
	GetPrefixesByLargeCommunity(context.Context, *LargeCommunityRequest) (*RoutesResponse, error)
	// GetInvalidPrefixes returns all IPv4 and IPv6 prefixes with local_pref = 50 (lightweight).
	GetInvalidPrefixes(context.Context, *OriginRequest) (*PrefixesResponse, error)
	mustEmbedUnimplementedBGPWatchServer()
}

// UnimplementedBGPWatchServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBGPWatchServer struct{}

func (UnimplementedBGPWatchServer) GetTotals(context.Context, *Empty) (*TotalsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTotals not implemented")
}
func (UnimplementedBGPWatchServer) GetMasks(context.Context, *Empty) (*MasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMasks not implemented")
}
func (UnimplementedBGPWatchServer) GetSystemStats(context.Context, *Empty) (*SystemStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSystemStats not implemented")
}
func (UnimplementedBGPWatchServer) GetRoute(context.Context, *RouteRequest) (*RouteLookupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoute not implemented")
}
func (UnimplementedBGPWatchServer) GetRoutes(context.Context, *RouteRequest) (*RoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutes not implemented")
}
func (UnimplementedBGPWatchServer) GetPrefixesByOrigin(context.Context, *OriginRequest) (*PrefixesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrefixesByOrigin not implemented")
}
func (UnimplementedBGPWatchServer) GetRoutesByOrigin(context.Context, *OriginRequest) (*RoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutesByOrigin not implemented")
}
func (UnimplementedBGPWatchServer) GetPrefixesByAsPath(context.Context, *AsPathRequest) (*RoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrefixesByAsPath not implemented")
}
func (UnimplementedBGPWatchServer) GetPrefixesByCommunity(context.Context, *CommunityRequest) (*RoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrefixesByCommunity not implemented")
}
func (UnimplementedBGPWatchServer) GetPrefixesByLargeCommunity(context.Context, *LargeCommunityRequest) (*RoutesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrefixesByLargeCommunity not implemented")
}
func (UnimplementedBGPWatchServer) GetInvalidPrefixes(context.Context, *OriginRequest) (*PrefixesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInvalidPrefixes not implemented")
}
func (UnimplementedBGPWatchServer) mustEmbedUnimplementedBGPWatchServer() {}
func (UnimplementedBGPWatchServer) testEmbeddedByValue()                  {}

// UnsafeBGPWatchServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BGPWatchServer will
// result in compilation errors.
type UnsafeBGPWatchServer interface {
	mustEmbedUnimplementedBGPWatchServer()
}

func RegisterBGPWatchServer(s grpc.ServiceRegistrar, srv BGPWatchServer) {
	// If the following call panics, it indicates UnimplementedBGPWatchServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BGPWatch_ServiceDesc, srv)
}

func _BGPWatch_GetTotals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetTotals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetTotals_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetTotals(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPWatch_GetMasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetMasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetMasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetMasks(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPWatch_GetSystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetSystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetSystemStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetSystemStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPWatch_GetRoute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetRoute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetRoute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetRoute(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPWatch_GetRoutes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RouteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetRoutes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetRoutes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetRoutes(ctx, req.(*RouteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPWatch_GetPrefixesByOrigin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetPrefixesByOrigin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetPrefixesByOrigin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetPrefixesByOrigin(ctx, req.(*OriginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPWatch_GetRoutesByOrigin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetRoutesByOrigin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetRoutesByOrigin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetRoutesByOrigin(ctx, req.(*OriginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPWatch_GetPrefixesByAsPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AsPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetPrefixesByAsPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetPrefixesByAsPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetPrefixesByAsPath(ctx, req.(*AsPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPWatch_GetPrefixesByCommunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommunityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetPrefixesByCommunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetPrefixesByCommunity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetPrefixesByCommunity(ctx, req.(*CommunityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPWatch_GetPrefixesByLargeCommunity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LargeCommunityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetPrefixesByLargeCommunity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetPrefixesByLargeCommunity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetPrefixesByLargeCommunity(ctx, req.(*LargeCommunityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BGPWatch_GetInvalidPrefixes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OriginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BGPWatchServer).GetInvalidPrefixes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BGPWatch_GetInvalidPrefixes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BGPWatchServer).GetInvalidPrefixes(ctx, req.(*OriginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BGPWatch_ServiceDesc is the grpc.ServiceDesc for BGPWatch service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BGPWatch_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bgpwatch.BGPWatch",
	HandlerType: (*BGPWatchServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTotals",
			Handler:    _BGPWatch_GetTotals_Handler,
		},
		{
			MethodName: "GetMasks",
			Handler:    _BGPWatch_GetMasks_Handler,
		},
		{
			MethodName: "GetSystemStats",
			Handler:    _BGPWatch_GetSystemStats_Handler,
		},
		{
			MethodName: "GetRoute",
			Handler:    _BGPWatch_GetRoute_Handler,
		},
		{
			MethodName: "GetRoutes",
			Handler:    _BGPWatch_GetRoutes_Handler,
		},
		{
			MethodName: "GetPrefixesByOrigin",
			Handler:    _BGPWatch_GetPrefixesByOrigin_Handler,
		},
		{
			MethodName: "GetRoutesByOrigin",
			Handler:    _BGPWatch_GetRoutesByOrigin_Handler,
		},
		{
			MethodName: "GetPrefixesByAsPath",
			Handler:    _BGPWatch_GetPrefixesByAsPath_Handler,
		},
		{
			MethodName: "GetPrefixesByCommunity",
			Handler:    _BGPWatch_GetPrefixesByCommunity_Handler,
		},
		{
			MethodName: "GetPrefixesByLargeCommunity",
			Handler:    _BGPWatch_GetPrefixesByLargeCommunity_Handler,
		},
		{
			MethodName: "GetInvalidPrefixes",
			Handler:    _BGPWatch_GetInvalidPrefixes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/bgpwatch.proto",
}
