// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bgpwatch.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type TotalsResponse struct {
	Ipv4Count            int32    `protobuf:"varint,1,opt,name=ipv4_count,json=ipv4Count,proto3" json:"ipv4_count,omitempty"`
	Ipv6Count            int32    `protobuf:"varint,2,opt,name=ipv6_count,json=ipv6Count,proto3" json:"ipv6_count,omitempty"`
	TotalIpv4Paths       int64    `protobuf:"varint,3,opt,name=total_ipv4_paths,json=totalIpv4Paths,proto3" json:"total_ipv4_paths,omitempty"`
	TotalIpv6Paths       int64    `protobuf:"varint,4,opt,name=total_ipv6_paths,json=totalIpv6Paths,proto3" json:"total_ipv6_paths,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalsResponse) Reset()         { *m = TotalsResponse{} }
func (m *TotalsResponse) String() string { return proto.CompactTextString(m) }
func (*TotalsResponse) ProtoMessage()    {}
func (*TotalsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{1}
}

func (m *TotalsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalsResponse.Unmarshal(m, b)
}
func (m *TotalsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalsResponse.Marshal(b, m, deterministic)
}
func (m *TotalsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalsResponse.Merge(m, src)
}
func (m *TotalsResponse) XXX_Size() int {
	return xxx_messageInfo_TotalsResponse.Size(m)
}
func (m *TotalsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TotalsResponse proto.InternalMessageInfo

func (m *TotalsResponse) GetIpv4Count() int32 {
	if m != nil {
		return m.Ipv4Count
	}
	return 0
}

func (m *TotalsResponse) GetIpv6Count() int32 {
	if m != nil {
		return m.Ipv6Count
	}
	return 0
}

func (m *TotalsResponse) GetTotalIpv4Paths() int64 {
	if m != nil {
		return m.TotalIpv4Paths
	}
	return 0
}

func (m *TotalsResponse) GetTotalIpv6Paths() int64 {
	if m != nil {
		return m.TotalIpv6Paths
	}
	return 0
}

type MasksResponse struct {
	Ipv4Masks            map[int32]int32 `protobuf:"bytes,1,rep,name=ipv4_masks,json=ipv4Masks,proto3" json:"ipv4_masks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Ipv6Masks            map[int32]int32 `protobuf:"bytes,2,rep,name=ipv6_masks,json=ipv6Masks,proto3" json:"ipv6_masks,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *MasksResponse) Reset()         { *m = MasksResponse{} }
func (m *MasksResponse) String() string { return proto.CompactTextString(m) }
func (*MasksResponse) ProtoMessage()    {}
func (*MasksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{2}
}

func (m *MasksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MasksResponse.Unmarshal(m, b)
}
func (m *MasksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MasksResponse.Marshal(b, m, deterministic)
}
func (m *MasksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MasksResponse.Merge(m, src)
}
func (m *MasksResponse) XXX_Size() int {
	return xxx_messageInfo_MasksResponse.Size(m)
}
func (m *MasksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MasksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MasksResponse proto.InternalMessageInfo

func (m *MasksResponse) GetIpv4Masks() map[int32]int32 {
	if m != nil {
		return m.Ipv4Masks
	}
	return nil
}

func (m *MasksResponse) GetIpv6Masks() map[int32]int32 {
	if m != nil {
		return m.Ipv6Masks
	}
	return nil
}

// RouteRequest specifies a route to look up.
// If address contains a prefix length (e.g. "1.1.2.0/24"), an exact prefix match is performed.
// If address is a bare IP (e.g. "1.1.1.1"), a longest prefix match (LPM) is performed.
type RouteRequest struct {
	Address              string   `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteRequest) Reset()         { *m = RouteRequest{} }
func (m *RouteRequest) String() string { return proto.CompactTextString(m) }
func (*RouteRequest) ProtoMessage()    {}
func (*RouteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{3}
}

func (m *RouteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteRequest.Unmarshal(m, b)
}
func (m *RouteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteRequest.Marshal(b, m, deterministic)
}
func (m *RouteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteRequest.Merge(m, src)
}
func (m *RouteRequest) XXX_Size() int {
	return xxx_messageInfo_RouteRequest.Size(m)
}
func (m *RouteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RouteRequest proto.InternalMessageInfo

func (m *RouteRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type Community struct {
	High                 uint32   `protobuf:"varint,1,opt,name=high,proto3" json:"high,omitempty"`
	Low                  uint32   `protobuf:"varint,2,opt,name=low,proto3" json:"low,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Community) Reset()         { *m = Community{} }
func (m *Community) String() string { return proto.CompactTextString(m) }
func (*Community) ProtoMessage()    {}
func (*Community) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{4}
}

func (m *Community) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Community.Unmarshal(m, b)
}
func (m *Community) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Community.Marshal(b, m, deterministic)
}
func (m *Community) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Community.Merge(m, src)
}
func (m *Community) XXX_Size() int {
	return xxx_messageInfo_Community.Size(m)
}
func (m *Community) XXX_DiscardUnknown() {
	xxx_messageInfo_Community.DiscardUnknown(m)
}

var xxx_messageInfo_Community proto.InternalMessageInfo

func (m *Community) GetHigh() uint32 {
	if m != nil {
		return m.High
	}
	return 0
}

func (m *Community) GetLow() uint32 {
	if m != nil {
		return m.Low
	}
	return 0
}

type LargeCommunity struct {
	GlobalAdmin          uint32   `protobuf:"varint,1,opt,name=global_admin,json=globalAdmin,proto3" json:"global_admin,omitempty"`
	LocalData1           uint32   `protobuf:"varint,2,opt,name=local_data1,json=localData1,proto3" json:"local_data1,omitempty"`
	LocalData2           uint32   `protobuf:"varint,3,opt,name=local_data2,json=localData2,proto3" json:"local_data2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LargeCommunity) Reset()         { *m = LargeCommunity{} }
func (m *LargeCommunity) String() string { return proto.CompactTextString(m) }
func (*LargeCommunity) ProtoMessage()    {}
func (*LargeCommunity) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{5}
}

func (m *LargeCommunity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LargeCommunity.Unmarshal(m, b)
}
func (m *LargeCommunity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LargeCommunity.Marshal(b, m, deterministic)
}
func (m *LargeCommunity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LargeCommunity.Merge(m, src)
}
func (m *LargeCommunity) XXX_Size() int {
	return xxx_messageInfo_LargeCommunity.Size(m)
}
func (m *LargeCommunity) XXX_DiscardUnknown() {
	xxx_messageInfo_LargeCommunity.DiscardUnknown(m)
}

var xxx_messageInfo_LargeCommunity proto.InternalMessageInfo

func (m *LargeCommunity) GetGlobalAdmin() uint32 {
	if m != nil {
		return m.GlobalAdmin
	}
	return 0
}

func (m *LargeCommunity) GetLocalData1() uint32 {
	if m != nil {
		return m.LocalData1
	}
	return 0
}

func (m *LargeCommunity) GetLocalData2() uint32 {
	if m != nil {
		return m.LocalData2
	}
	return 0
}

type CommunityRequest struct {
	Community            uint32   `protobuf:"varint,1,opt,name=community,proto3" json:"community,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommunityRequest) Reset()         { *m = CommunityRequest{} }
func (m *CommunityRequest) String() string { return proto.CompactTextString(m) }
func (*CommunityRequest) ProtoMessage()    {}
func (*CommunityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{6}
}

func (m *CommunityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommunityRequest.Unmarshal(m, b)
}
func (m *CommunityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommunityRequest.Marshal(b, m, deterministic)
}
func (m *CommunityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommunityRequest.Merge(m, src)
}
func (m *CommunityRequest) XXX_Size() int {
	return xxx_messageInfo_CommunityRequest.Size(m)
}
func (m *CommunityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CommunityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CommunityRequest proto.InternalMessageInfo

func (m *CommunityRequest) GetCommunity() uint32 {
	if m != nil {
		return m.Community
	}
	return 0
}

type LargeCommunityRequest struct {
	Community            *LargeCommunity `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *LargeCommunityRequest) Reset()         { *m = LargeCommunityRequest{} }
func (m *LargeCommunityRequest) String() string { return proto.CompactTextString(m) }
func (*LargeCommunityRequest) ProtoMessage()    {}
func (*LargeCommunityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{7}
}

func (m *LargeCommunityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LargeCommunityRequest.Unmarshal(m, b)
}
func (m *LargeCommunityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LargeCommunityRequest.Marshal(b, m, deterministic)
}
func (m *LargeCommunityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LargeCommunityRequest.Merge(m, src)
}
func (m *LargeCommunityRequest) XXX_Size() int {
	return xxx_messageInfo_LargeCommunityRequest.Size(m)
}
func (m *LargeCommunityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LargeCommunityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LargeCommunityRequest proto.InternalMessageInfo

func (m *LargeCommunityRequest) GetCommunity() *LargeCommunity {
	if m != nil {
		return m.Community
	}
	return nil
}

type Route struct {
	Prefix               string            `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	AsPath               []uint32          `protobuf:"varint,2,rep,packed,name=as_path,json=asPath,proto3" json:"as_path,omitempty"`
	LocalPref            uint32            `protobuf:"varint,3,opt,name=local_pref,json=localPref,proto3" json:"local_pref,omitempty"`
	Communities          []*Community      `protobuf:"bytes,4,rep,name=communities,proto3" json:"communities,omitempty"`
	LargeCommunities     []*LargeCommunity `protobuf:"bytes,5,rep,name=large_communities,json=largeCommunities,proto3" json:"large_communities,omitempty"`
	PeerIp               string            `protobuf:"bytes,6,opt,name=peer_ip,json=peerIp,proto3" json:"peer_ip,omitempty"`
	PathId               uint32            `protobuf:"varint,7,opt,name=path_id,json=pathId,proto3" json:"path_id,omitempty"`
	StaleSeconds         uint64            `protobuf:"varint,8,opt,name=stale_seconds,json=staleSeconds,proto3" json:"stale_seconds,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Route) Reset()         { *m = Route{} }
func (m *Route) String() string { return proto.CompactTextString(m) }
func (*Route) ProtoMessage()    {}
func (*Route) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{8}
}

func (m *Route) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Route.Unmarshal(m, b)
}
func (m *Route) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Route.Marshal(b, m, deterministic)
}
func (m *Route) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Route.Merge(m, src)
}
func (m *Route) XXX_Size() int {
	return xxx_messageInfo_Route.Size(m)
}
func (m *Route) XXX_DiscardUnknown() {
	xxx_messageInfo_Route.DiscardUnknown(m)
}

var xxx_messageInfo_Route proto.InternalMessageInfo

func (m *Route) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Route) GetAsPath() []uint32 {
	if m != nil {
		return m.AsPath
	}
	return nil
}

func (m *Route) GetLocalPref() uint32 {
	if m != nil {
		return m.LocalPref
	}
	return 0
}

func (m *Route) GetCommunities() []*Community {
	if m != nil {
		return m.Communities
	}
	return nil
}

func (m *Route) GetLargeCommunities() []*LargeCommunity {
	if m != nil {
		return m.LargeCommunities
	}
	return nil
}

func (m *Route) GetPeerIp() string {
	if m != nil {
		return m.PeerIp
	}
	return ""
}

func (m *Route) GetPathId() uint32 {
	if m != nil {
		return m.PathId
	}
	return 0
}

func (m *Route) GetStaleSeconds() uint64 {
	if m != nil {
		return m.StaleSeconds
	}
	return 0
}

type RouteLookupResponse struct {
	Found                bool     `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Route                *Route   `protobuf:"bytes,2,opt,name=route,proto3" json:"route,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteLookupResponse) Reset()         { *m = RouteLookupResponse{} }
func (m *RouteLookupResponse) String() string { return proto.CompactTextString(m) }
func (*RouteLookupResponse) ProtoMessage()    {}
func (*RouteLookupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{9}
}

func (m *RouteLookupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteLookupResponse.Unmarshal(m, b)
}
func (m *RouteLookupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteLookupResponse.Marshal(b, m, deterministic)
}
func (m *RouteLookupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteLookupResponse.Merge(m, src)
}
func (m *RouteLookupResponse) XXX_Size() int {
	return xxx_messageInfo_RouteLookupResponse.Size(m)
}
func (m *RouteLookupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteLookupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RouteLookupResponse proto.InternalMessageInfo

func (m *RouteLookupResponse) GetFound() bool {
	if m != nil {
		return m.Found
	}
	return false
}

func (m *RouteLookupResponse) GetRoute() *Route {
	if m != nil {
		return m.Route
	}
	return nil
}

type RoutesResponse struct {
	Routes               []*Route `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoutesResponse) Reset()         { *m = RoutesResponse{} }
func (m *RoutesResponse) String() string { return proto.CompactTextString(m) }
func (*RoutesResponse) ProtoMessage()    {}
func (*RoutesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{10}
}

func (m *RoutesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutesResponse.Unmarshal(m, b)
}
func (m *RoutesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutesResponse.Marshal(b, m, deterministic)
}
func (m *RoutesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutesResponse.Merge(m, src)
}
func (m *RoutesResponse) XXX_Size() int {
	return xxx_messageInfo_RoutesResponse.Size(m)
}
func (m *RoutesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoutesResponse proto.InternalMessageInfo

func (m *RoutesResponse) GetRoutes() []*Route {
	if m != nil {
		return m.Routes
	}
	return nil
}

type Prefix struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prefix) Reset()         { *m = Prefix{} }
func (m *Prefix) String() string { return proto.CompactTextString(m) }
func (*Prefix) ProtoMessage()    {}
func (*Prefix) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{11}
}

func (m *Prefix) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prefix.Unmarshal(m, b)
}
func (m *Prefix) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prefix.Marshal(b, m, deterministic)
}
func (m *Prefix) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prefix.Merge(m, src)
}
func (m *Prefix) XXX_Size() int {
	return xxx_messageInfo_Prefix.Size(m)
}
func (m *Prefix) XXX_DiscardUnknown() {
	xxx_messageInfo_Prefix.DiscardUnknown(m)
}

var xxx_messageInfo_Prefix proto.InternalMessageInfo

func (m *Prefix) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

type PrefixesResponse struct {
	Prefixes             []*Prefix `protobuf:"bytes,1,rep,name=prefixes,proto3" json:"prefixes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PrefixesResponse) Reset()         { *m = PrefixesResponse{} }
func (m *PrefixesResponse) String() string { return proto.CompactTextString(m) }
func (*PrefixesResponse) ProtoMessage()    {}
func (*PrefixesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{12}
}

func (m *PrefixesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrefixesResponse.Unmarshal(m, b)
}
func (m *PrefixesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrefixesResponse.Marshal(b, m, deterministic)
}
func (m *PrefixesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrefixesResponse.Merge(m, src)
}
func (m *PrefixesResponse) XXX_Size() int {
	return xxx_messageInfo_PrefixesResponse.Size(m)
}
func (m *PrefixesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PrefixesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PrefixesResponse proto.InternalMessageInfo

func (m *PrefixesResponse) GetPrefixes() []*Prefix {
	if m != nil {
		return m.Prefixes
	}
	return nil
}

type PeerStats struct {
	EstablishedDurationSeconds uint64   `protobuf:"varint,1,opt,name=established_duration_seconds,json=establishedDurationSeconds,proto3" json:"established_duration_seconds,omitempty"`
	TotalAdvertisements        uint64   `protobuf:"varint,2,opt,name=total_advertisements,json=totalAdvertisements,proto3" json:"total_advertisements,omitempty"`
	TotalWithdrawals           uint64   `protobuf:"varint,3,opt,name=total_withdrawals,json=totalWithdrawals,proto3" json:"total_withdrawals,omitempty"`
	RibRamBytes                uint64   `protobuf:"varint,4,opt,name=rib_ram_bytes,json=ribRamBytes,proto3" json:"rib_ram_bytes,omitempty"`
	AddPath                    bool     `protobuf:"varint,5,opt,name=add_path,json=addPath,proto3" json:"add_path,omitempty"`
	UniqueAttributes           uint64   `protobuf:"varint,6,opt,name=unique_attributes,json=uniqueAttributes,proto3" json:"unique_attributes,omitempty"`
	GracefulRestart            bool     `protobuf:"varint,7,opt,name=graceful_restart,json=gracefulRestart,proto3" json:"graceful_restart,omitempty"`
	Ipv4Eor                    bool     `protobuf:"varint,8,opt,name=ipv4_eor,json=ipv4Eor,proto3" json:"ipv4_eor,omitempty"`
	Ipv6Eor                    bool     `protobuf:"varint,9,opt,name=ipv6_eor,json=ipv6Eor,proto3" json:"ipv6_eor,omitempty"`
	Name                       string   `protobuf:"bytes,10,opt,name=name,proto3" json:"name,omitempty"`
	GrActive                   bool     `protobuf:"varint,11,opt,name=gr_active,json=grActive,proto3" json:"gr_active,omitempty"`
	State                      string   `protobuf:"bytes,12,opt,name=state,proto3" json:"state,omitempty"`
	MsgRecv                    uint64   `protobuf:"varint,13,opt,name=msg_recv,json=msgRecv,proto3" json:"msg_recv,omitempty"`
	InUpdates                  uint64   `protobuf:"varint,14,opt,name=in_updates,json=inUpdates,proto3" json:"in_updates,omitempty"`
	Flaps                      uint32   `protobuf:"varint,15,opt,name=flaps,proto3" json:"flaps,omitempty"`
	LastNotification           string   `protobuf:"bytes,16,opt,name=last_notification,json=lastNotification,proto3" json:"last_notification,omitempty"`
	PrefixCount                uint64   `protobuf:"varint,17,opt,name=prefix_count,json=prefixCount,proto3" json:"prefix_count,omitempty"`
	PathCount                  uint64   `protobuf:"varint,18,opt,name=path_count,json=pathCount,proto3" json:"path_count,omitempty"`
	XXX_NoUnkeyedLiteral       struct{} `json:"-"`
	XXX_unrecognized           []byte   `json:"-"`
	XXX_sizecache              int32    `json:"-"`
}

func (m *PeerStats) Reset()         { *m = PeerStats{} }
func (m *PeerStats) String() string { return proto.CompactTextString(m) }
func (*PeerStats) ProtoMessage()    {}
func (*PeerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{13}
}

func (m *PeerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerStats.Unmarshal(m, b)
}
func (m *PeerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerStats.Marshal(b, m, deterministic)
}
func (m *PeerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerStats.Merge(m, src)
}
func (m *PeerStats) XXX_Size() int {
	return xxx_messageInfo_PeerStats.Size(m)
}
func (m *PeerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerStats.DiscardUnknown(m)
}

var xxx_messageInfo_PeerStats proto.InternalMessageInfo

func (m *PeerStats) GetEstablishedDurationSeconds() uint64 {
	if m != nil {
		return m.EstablishedDurationSeconds
	}
	return 0
}

func (m *PeerStats) GetTotalAdvertisements() uint64 {
	if m != nil {
		return m.TotalAdvertisements
	}
	return 0
}

func (m *PeerStats) GetTotalWithdrawals() uint64 {
	if m != nil {
		return m.TotalWithdrawals
	}
	return 0
}

func (m *PeerStats) GetRibRamBytes() uint64 {
	if m != nil {
		return m.RibRamBytes
	}
	return 0
}

func (m *PeerStats) GetAddPath() bool {
	if m != nil {
		return m.AddPath
	}
	return false
}

func (m *PeerStats) GetUniqueAttributes() uint64 {
	if m != nil {
		return m.UniqueAttributes
	}
	return 0
}

func (m *PeerStats) GetGracefulRestart() bool {
	if m != nil {
		return m.GracefulRestart
	}
	return false
}

func (m *PeerStats) GetIpv4Eor() bool {
	if m != nil {
		return m.Ipv4Eor
	}
	return false
}

func (m *PeerStats) GetIpv6Eor() bool {
	if m != nil {
		return m.Ipv6Eor
	}
	return false
}

func (m *PeerStats) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PeerStats) GetGrActive() bool {
	if m != nil {
		return m.GrActive
	}
	return false
}

func (m *PeerStats) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *PeerStats) GetMsgRecv() uint64 {
	if m != nil {
		return m.MsgRecv
	}
	return 0
}

func (m *PeerStats) GetInUpdates() uint64 {
	if m != nil {
		return m.InUpdates
	}
	return 0
}

func (m *PeerStats) GetFlaps() uint32 {
	if m != nil {
		return m.Flaps
	}
	return 0
}

func (m *PeerStats) GetLastNotification() string {
	if m != nil {
		return m.LastNotification
	}
	return ""
}

func (m *PeerStats) GetPrefixCount() uint64 {
	if m != nil {
		return m.PrefixCount
	}
	return 0
}

func (m *PeerStats) GetPathCount() uint64 {
	if m != nil {
		return m.PathCount
	}
	return 0
}

type SystemStatsResponse struct {
	TotalAppRamBytes     uint64                `protobuf:"varint,1,opt,name=total_app_ram_bytes,json=totalAppRamBytes,proto3" json:"total_app_ram_bytes,omitempty"`
	HeapAllocBytes       uint64                `protobuf:"varint,2,opt,name=heap_alloc_bytes,json=heapAllocBytes,proto3" json:"heap_alloc_bytes,omitempty"`
	HeapSysBytes         uint64                `protobuf:"varint,3,opt,name=heap_sys_bytes,json=heapSysBytes,proto3" json:"heap_sys_bytes,omitempty"`
	HeapIdleBytes        uint64                `protobuf:"varint,4,opt,name=heap_idle_bytes,json=heapIdleBytes,proto3" json:"heap_idle_bytes,omitempty"`
	HeapReleasedBytes    uint64                `protobuf:"varint,5,opt,name=heap_released_bytes,json=heapReleasedBytes,proto3" json:"heap_released_bytes,omitempty"`
	NumGc                uint32                `protobuf:"varint,6,opt,name=num_gc,json=numGc,proto3" json:"num_gc,omitempty"`
	TotalPeerRibRamBytes uint64                `protobuf:"varint,7,opt,name=total_peer_rib_ram_bytes,json=totalPeerRibRamBytes,proto3" json:"total_peer_rib_ram_bytes,omitempty"`
	PeerStats            map[string]*PeerStats `protobuf:"bytes,8,rep,name=peer_stats,json=peerStats,proto3" json:"peer_stats,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PssBytes             uint64                `protobuf:"varint,9,opt,name=pss_bytes,json=pssBytes,proto3" json:"pss_bytes,omitempty"`
	RssBytes             uint64                `protobuf:"varint,10,opt,name=rss_bytes,json=rssBytes,proto3" json:"rss_bytes,omitempty"`
	HeapObjects          uint64                `protobuf:"varint,11,opt,name=heap_objects,json=heapObjects,proto3" json:"heap_objects,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *SystemStatsResponse) Reset()         { *m = SystemStatsResponse{} }
func (m *SystemStatsResponse) String() string { return proto.CompactTextString(m) }
func (*SystemStatsResponse) ProtoMessage()    {}
func (*SystemStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{14}
}

func (m *SystemStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemStatsResponse.Unmarshal(m, b)
}
func (m *SystemStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemStatsResponse.Marshal(b, m, deterministic)
}
func (m *SystemStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemStatsResponse.Merge(m, src)
}
func (m *SystemStatsResponse) XXX_Size() int {
	return xxx_messageInfo_SystemStatsResponse.Size(m)
}
func (m *SystemStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SystemStatsResponse proto.InternalMessageInfo

func (m *SystemStatsResponse) GetTotalAppRamBytes() uint64 {
	if m != nil {
		return m.TotalAppRamBytes
	}
	return 0
}

func (m *SystemStatsResponse) GetHeapAllocBytes() uint64 {
	if m != nil {
		return m.HeapAllocBytes
	}
	return 0
}

func (m *SystemStatsResponse) GetHeapSysBytes() uint64 {
	if m != nil {
		return m.HeapSysBytes
	}
	return 0
}

func (m *SystemStatsResponse) GetHeapIdleBytes() uint64 {
	if m != nil {
		return m.HeapIdleBytes
	}
	return 0
}

func (m *SystemStatsResponse) GetHeapReleasedBytes() uint64 {
	if m != nil {
		return m.HeapReleasedBytes
	}
	return 0
}

func (m *SystemStatsResponse) GetNumGc() uint32 {
	if m != nil {
		return m.NumGc
	}
	return 0
}

func (m *SystemStatsResponse) GetTotalPeerRibRamBytes() uint64 {
	if m != nil {
		return m.TotalPeerRibRamBytes
	}
	return 0
}

func (m *SystemStatsResponse) GetPeerStats() map[string]*PeerStats {
	if m != nil {
		return m.PeerStats
	}
	return nil
}

func (m *SystemStatsResponse) GetPssBytes() uint64 {
	if m != nil {
		return m.PssBytes
	}
	return 0
}

func (m *SystemStatsResponse) GetRssBytes() uint64 {
	if m != nil {
		return m.RssBytes
	}
	return 0
}

func (m *SystemStatsResponse) GetHeapObjects() uint64 {
	if m != nil {
		return m.HeapObjects
	}
	return 0
}

type AsPathRequest struct {
	Regex                string   `protobuf:"bytes,1,opt,name=regex,proto3" json:"regex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AsPathRequest) Reset()         { *m = AsPathRequest{} }
func (m *AsPathRequest) String() string { return proto.CompactTextString(m) }
func (*AsPathRequest) ProtoMessage()    {}
func (*AsPathRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{15}
}

func (m *AsPathRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AsPathRequest.Unmarshal(m, b)
}
func (m *AsPathRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AsPathRequest.Marshal(b, m, deterministic)
}
func (m *AsPathRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AsPathRequest.Merge(m, src)
}
func (m *AsPathRequest) XXX_Size() int {
	return xxx_messageInfo_AsPathRequest.Size(m)
}
func (m *AsPathRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AsPathRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AsPathRequest proto.InternalMessageInfo

func (m *AsPathRequest) GetRegex() string {
	if m != nil {
		return m.Regex
	}
	return ""
}

// OriginRequest specifies an ASN to query for originated prefixes.
type OriginRequest struct {
	Asn                  uint32   `protobuf:"varint,1,opt,name=asn,proto3" json:"asn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OriginRequest) Reset()         { *m = OriginRequest{} }
func (m *OriginRequest) String() string { return proto.CompactTextString(m) }
func (*OriginRequest) ProtoMessage()    {}
func (*OriginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef63b93f35f87fb9, []int{16}
}

func (m *OriginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OriginRequest.Unmarshal(m, b)
}
func (m *OriginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OriginRequest.Marshal(b, m, deterministic)
}
func (m *OriginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OriginRequest.Merge(m, src)
}
func (m *OriginRequest) XXX_Size() int {
	return xxx_messageInfo_OriginRequest.Size(m)
}
func (m *OriginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OriginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OriginRequest proto.InternalMessageInfo

func (m *OriginRequest) GetAsn() uint32 {
	if m != nil {
		return m.Asn
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "bgpwatch.Empty")
	proto.RegisterType((*TotalsResponse)(nil), "bgpwatch.TotalsResponse")
	proto.RegisterType((*MasksResponse)(nil), "bgpwatch.MasksResponse")
	proto.RegisterMapType((map[int32]int32)(nil), "bgpwatch.MasksResponse.Ipv4MasksEntry")
	proto.RegisterMapType((map[int32]int32)(nil), "bgpwatch.MasksResponse.Ipv6MasksEntry")
	proto.RegisterType((*RouteRequest)(nil), "bgpwatch.RouteRequest")
	proto.RegisterType((*Community)(nil), "bgpwatch.Community")
	proto.RegisterType((*LargeCommunity)(nil), "bgpwatch.LargeCommunity")
	proto.RegisterType((*CommunityRequest)(nil), "bgpwatch.CommunityRequest")
	proto.RegisterType((*LargeCommunityRequest)(nil), "bgpwatch.LargeCommunityRequest")
	proto.RegisterType((*Route)(nil), "bgpwatch.Route")
	proto.RegisterType((*RouteLookupResponse)(nil), "bgpwatch.RouteLookupResponse")
	proto.RegisterType((*RoutesResponse)(nil), "bgpwatch.RoutesResponse")
	proto.RegisterType((*Prefix)(nil), "bgpwatch.Prefix")
	proto.RegisterType((*PrefixesResponse)(nil), "bgpwatch.PrefixesResponse")
	proto.RegisterType((*PeerStats)(nil), "bgpwatch.PeerStats")
	proto.RegisterType((*SystemStatsResponse)(nil), "bgpwatch.SystemStatsResponse")
	proto.RegisterMapType((map[string]*PeerStats)(nil), "bgpwatch.SystemStatsResponse.PeerStatsEntry")
	proto.RegisterType((*AsPathRequest)(nil), "bgpwatch.AsPathRequest")
	proto.RegisterType((*OriginRequest)(nil), "bgpwatch.OriginRequest")
}

func init() {
	proto.RegisterFile("proto/bgpwatch.proto", fileDescriptor_ef63b93f35f87fb9)
}

var fileDescriptor_ef63b93f35f87fb9 = []byte{
	// 1431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x72, 0x13, 0x47,
	0x16, 0x2e, 0xd9, 0xfa, 0x3d, 0xb2, 0x64, 0xb9, 0x6d, 0x60, 0xd6, 0x86, 0xc2, 0xcc, 0x2e, 0x60,
	0x0a, 0xd6, 0x2c, 0x5e, 0x56, 0xb5, 0xbb, 0x95, 0x54, 0x21, 0x83, 0xe3, 0x38, 0x21, 0xe0, 0x8c,
	0x93, 0x22, 0x95, 0x9b, 0xa9, 0xd6, 0x4c, 0x5b, 0x9a, 0x30, 0x7f, 0x74, 0xf7, 0xc8, 0xd1, 0x5d,
	0xde, 0x20, 0xd7, 0xb9, 0xcd, 0x75, 0x1e, 0x20, 0x8f, 0x97, 0xea, 0xd3, 0x3d, 0xa3, 0x19, 0x81,
	0x71, 0x15, 0x57, 0x9a, 0xf3, 0x9d, 0xef, 0x9c, 0xd3, 0x7d, 0xfa, 0xeb, 0x1f, 0xc1, 0x56, 0xca,
	0x13, 0x99, 0x3c, 0x1e, 0x4f, 0xd2, 0x0b, 0x2a, 0xbd, 0xe9, 0x3e, 0x9a, 0xa4, 0x9d, 0xdb, 0x76,
	0x0b, 0x1a, 0x47, 0x51, 0x2a, 0xe7, 0xf6, 0xef, 0x35, 0xe8, 0x7f, 0x97, 0x48, 0x1a, 0x0a, 0x87,
	0x89, 0x34, 0x89, 0x05, 0x23, 0xb7, 0x00, 0x82, 0x74, 0xf6, 0xd4, 0xf5, 0x92, 0x2c, 0x96, 0x56,
	0x6d, 0xb7, 0xb6, 0xd7, 0x70, 0x3a, 0x0a, 0x79, 0xae, 0x00, 0xe3, 0x1e, 0x1a, 0xf7, 0x4a, 0xe1,
	0x1e, 0x6a, 0xf7, 0x1e, 0x0c, 0xa4, 0xca, 0xe7, 0x62, 0x8e, 0x94, 0xca, 0xa9, 0xb0, 0x56, 0x77,
	0x6b, 0x7b, 0xab, 0x4e, 0x1f, 0xf1, 0x93, 0x74, 0xf6, 0xf4, 0x54, 0xa1, 0x15, 0xe6, 0xd0, 0x30,
	0xeb, 0x55, 0xe6, 0x10, 0x99, 0xf6, 0x6f, 0x2b, 0xd0, 0xfb, 0x86, 0x8a, 0xb7, 0x8b, 0x31, 0x1e,
	0x99, 0x31, 0x46, 0x0a, 0xb5, 0x6a, 0xbb, 0xab, 0x7b, 0xdd, 0x83, 0x7b, 0xfb, 0xc5, 0x74, 0x2b,
	0xe4, 0x7d, 0x55, 0x12, 0x91, 0xa3, 0x58, 0xf2, 0xb9, 0x9e, 0x0b, 0xda, 0x26, 0xcd, 0xd0, 0xa4,
	0x59, 0xb9, 0x32, 0xcd, 0x70, 0x29, 0x8d, 0xb6, 0xb7, 0x3f, 0x83, 0x7e, 0xb5, 0x06, 0x19, 0xc0,
	0xea, 0x5b, 0x36, 0x37, 0xcd, 0x53, 0x9f, 0x64, 0x0b, 0x1a, 0x33, 0x1a, 0x66, 0xcc, 0x74, 0x4c,
	0x1b, 0xff, 0x5f, 0xf9, 0x6f, 0xcd, 0x44, 0x0f, 0x3f, 0x2d, 0xda, 0xde, 0x83, 0x35, 0x27, 0xc9,
	0x24, 0x73, 0xd8, 0xbb, 0x8c, 0x09, 0x49, 0x2c, 0x68, 0x51, 0xdf, 0xe7, 0x4c, 0x08, 0x8c, 0xef,
	0x38, 0xb9, 0x69, 0x3f, 0x81, 0xce, 0xf3, 0x24, 0x8a, 0xb2, 0x38, 0x90, 0x73, 0x42, 0xa0, 0x3e,
	0x0d, 0x26, 0x53, 0xe4, 0xf4, 0x1c, 0xfc, 0x56, 0x65, 0xc3, 0xe4, 0x02, 0x4b, 0xf4, 0x1c, 0xf5,
	0x69, 0x67, 0xd0, 0x7f, 0x49, 0xf9, 0x84, 0x2d, 0xe2, 0xee, 0xc0, 0xda, 0x24, 0x4c, 0xc6, 0x34,
	0x74, 0xa9, 0x1f, 0x05, 0xb1, 0x89, 0xef, 0x6a, 0x6c, 0xa4, 0x20, 0x72, 0x1b, 0xba, 0x61, 0xe2,
	0xd1, 0xd0, 0xf5, 0xa9, 0xa4, 0x4f, 0x4c, 0x3a, 0x40, 0xe8, 0x85, 0x42, 0xaa, 0x84, 0x03, 0x54,
	0x47, 0x99, 0x70, 0x60, 0xff, 0x0b, 0x06, 0x45, 0xc5, 0x7c, 0x5e, 0x37, 0xa1, 0xe3, 0xe5, 0x98,
	0xa9, 0xba, 0x00, 0xec, 0xd7, 0x70, 0xad, 0x3a, 0xd0, 0x3c, 0x6c, 0xb8, 0x1c, 0xd6, 0x3d, 0xb0,
	0x16, 0x0b, 0xbc, 0x14, 0x53, 0x4a, 0xf8, 0xc7, 0x0a, 0x34, 0xb0, 0xaf, 0xe4, 0x3a, 0x34, 0x53,
	0xce, 0xce, 0x83, 0x9f, 0x4d, 0x3f, 0x8d, 0x45, 0x6e, 0x40, 0x8b, 0x0a, 0x94, 0x2d, 0x0a, 0xa7,
	0xe7, 0x34, 0xa9, 0x50, 0x72, 0x55, 0x1b, 0x44, 0x4f, 0x4f, 0x11, 0xcd, 0xec, 0x3a, 0x88, 0x9c,
	0x72, 0x76, 0x4e, 0xfe, 0x03, 0xdd, 0xbc, 0x4c, 0xc0, 0x94, 0xe2, 0x95, 0xe8, 0x36, 0x17, 0x63,
	0x5a, 0x0c, 0xa7, 0xcc, 0x23, 0x47, 0xb0, 0x11, 0xaa, 0xd1, 0xba, 0xe5, 0xe0, 0x06, 0x06, 0x5f,
	0x3e, 0xa1, 0x41, 0x58, 0xb6, 0x55, 0x9a, 0x1b, 0xd0, 0x4a, 0x19, 0xe3, 0x6e, 0x90, 0x5a, 0x4d,
	0x33, 0x1d, 0xc6, 0xf8, 0x49, 0x8a, 0x0e, 0x2a, 0xa7, 0x6e, 0xe0, 0x5b, 0x2d, 0x1c, 0x72, 0x53,
	0x99, 0x27, 0x3e, 0xf9, 0x3b, 0xf4, 0x84, 0xa4, 0x21, 0x73, 0x05, 0xf3, 0x92, 0xd8, 0x17, 0x56,
	0x7b, 0xb7, 0xb6, 0x57, 0x77, 0xd6, 0x10, 0x3c, 0xd3, 0x98, 0xed, 0xc0, 0x26, 0x76, 0xeb, 0x65,
	0x92, 0xbc, 0xcd, 0xd2, 0x62, 0x9b, 0x6e, 0x41, 0xe3, 0x3c, 0xc9, 0x62, 0x1f, 0x5b, 0xd7, 0x76,
	0xb4, 0x41, 0xee, 0x42, 0x83, 0x2b, 0x32, 0x4a, 0xa3, 0x7b, 0xb0, 0xbe, 0x18, 0xbe, 0x56, 0xb2,
	0xf6, 0xda, 0xff, 0x83, 0x3e, 0xda, 0x8b, 0x5d, 0x7f, 0x1f, 0x9a, 0xe8, 0xca, 0x77, 0xfc, 0x7b,
	0x91, 0xc6, 0x6d, 0xef, 0x42, 0xf3, 0x54, 0xaf, 0xd2, 0x25, 0xab, 0x67, 0x3f, 0x83, 0x81, 0x66,
	0x94, 0xd2, 0x3f, 0x82, 0x76, 0x6a, 0x30, 0x53, 0x60, 0xb0, 0x28, 0xa0, 0xd9, 0x4e, 0xc1, 0xb0,
	0x7f, 0x69, 0x40, 0xe7, 0x94, 0x31, 0x7e, 0x26, 0xa9, 0x14, 0xe4, 0x19, 0xdc, 0x64, 0x42, 0xd2,
	0x71, 0x18, 0x88, 0x29, 0xf3, 0x5d, 0x3f, 0xe3, 0x54, 0x06, 0x49, 0x5c, 0x34, 0xad, 0x86, 0x4d,
	0xdb, 0x2e, 0x71, 0x5e, 0x18, 0x8a, 0x69, 0x21, 0x79, 0x02, 0x5b, 0xfa, 0x38, 0xa4, 0xfe, 0x8c,
	0x71, 0x19, 0x08, 0x16, 0xb1, 0x58, 0x0a, 0x6c, 0x52, 0xdd, 0xd9, 0x44, 0xdf, 0xa8, 0xe2, 0x22,
	0x0f, 0x61, 0x43, 0x87, 0x5c, 0x04, 0x72, 0xea, 0x73, 0x7a, 0x41, 0x43, 0x7d, 0xd8, 0xd6, 0x1d,
	0x7d, 0xb4, 0xbe, 0x59, 0xe0, 0xc4, 0x86, 0x1e, 0x0f, 0xc6, 0x2e, 0xa7, 0x91, 0x3b, 0x9e, 0x4b,
	0xa6, 0xcf, 0xda, 0xba, 0xd3, 0xe5, 0xc1, 0xd8, 0xa1, 0xd1, 0xa1, 0x82, 0xc8, 0xdf, 0xa0, 0x4d,
	0x7d, 0x5f, 0x8b, 0xba, 0x81, 0x4b, 0xa6, 0x4e, 0x0f, 0x54, 0xf5, 0x43, 0xd8, 0xc8, 0xe2, 0xe0,
	0x5d, 0xc6, 0x5c, 0x2a, 0x25, 0x0f, 0xc6, 0xb8, 0x0c, 0x4d, 0x5d, 0x4b, 0x3b, 0x46, 0x05, 0x4e,
	0x1e, 0xc0, 0x60, 0xc2, 0xa9, 0xc7, 0xce, 0xb3, 0xd0, 0xe5, 0x6a, 0xce, 0x5c, 0xa2, 0xaa, 0xda,
	0xce, 0x7a, 0x8e, 0x3b, 0x1a, 0x56, 0x25, 0xf1, 0x24, 0x67, 0x09, 0x47, 0x65, 0xb5, 0x9d, 0x96,
	0xb2, 0x8f, 0x12, 0x6e, 0x5c, 0x43, 0x74, 0x75, 0x0a, 0xd7, 0x50, 0xb9, 0x08, 0xd4, 0x63, 0x1a,
	0x31, 0x0b, 0x70, 0x51, 0xf1, 0x9b, 0xec, 0x40, 0x67, 0xc2, 0x5d, 0xea, 0xc9, 0x60, 0xc6, 0xac,
	0x2e, 0xf2, 0xdb, 0x13, 0x3e, 0x42, 0x5b, 0x29, 0x51, 0x48, 0x2a, 0x99, 0xb5, 0x86, 0x11, 0xda,
	0x50, 0x15, 0x22, 0x31, 0x71, 0x39, 0xf3, 0x66, 0x56, 0x0f, 0xe7, 0xd2, 0x8a, 0xc4, 0xc4, 0x61,
	0xde, 0x0c, 0xaf, 0xb9, 0xd8, 0xcd, 0x52, 0x9f, 0xaa, 0x89, 0xf6, 0xd1, 0xd9, 0x09, 0xe2, 0xef,
	0x35, 0x80, 0xca, 0x0e, 0x69, 0x2a, 0xac, 0x75, 0xdc, 0x2c, 0xda, 0x50, 0x4d, 0x0a, 0xa9, 0x90,
	0x6e, 0x9c, 0xc8, 0xe0, 0x3c, 0xf0, 0x70, 0x7d, 0xad, 0x01, 0x56, 0x1c, 0x28, 0xc7, 0xab, 0x12,
	0xae, 0x8e, 0x52, 0x2d, 0x26, 0x73, 0x95, 0x6e, 0xe8, 0xf5, 0xd0, 0x58, 0x71, 0xd7, 0xe2, 0xa6,
	0xd4, 0x04, 0xa2, 0x07, 0xa1, 0x10, 0x74, 0xdb, 0x7f, 0xd6, 0x61, 0xf3, 0x6c, 0x2e, 0x24, 0x8b,
	0x50, 0x84, 0x85, 0x90, 0xff, 0x09, 0x9b, 0x46, 0x4a, 0x69, 0x5a, 0x5a, 0xf0, 0x5a, 0x49, 0x19,
	0xa3, 0x34, 0x2d, 0x56, 0x7d, 0x0f, 0x06, 0x53, 0x46, 0x53, 0x97, 0x86, 0x61, 0xe2, 0x19, 0xae,
	0x56, 0x5d, 0x5f, 0xe1, 0x23, 0x05, 0x6b, 0xe6, 0x3f, 0x00, 0x11, 0x57, 0xcc, 0x85, 0xe1, 0x69,
	0xb5, 0xad, 0x29, 0xf4, 0x6c, 0x2e, 0x34, 0xeb, 0x1e, 0xac, 0x23, 0x2b, 0xf0, 0x43, 0x56, 0xd1,
	0x5a, 0x4f, 0xc1, 0x27, 0x7e, 0xc8, 0x34, 0x6f, 0x1f, 0x36, 0x91, 0xc7, 0x59, 0xc8, 0xa8, 0x60,
	0xbe, 0xe1, 0x36, 0x90, 0xbb, 0xa1, 0x5c, 0x8e, 0xf1, 0x68, 0xfe, 0x35, 0x68, 0xc6, 0x59, 0xe4,
	0x4e, 0x3c, 0xd4, 0x5d, 0xcf, 0x69, 0xc4, 0x59, 0x74, 0xec, 0x91, 0x21, 0x58, 0x7a, 0xb6, 0x78,
	0xb0, 0x55, 0x35, 0xde, 0xc2, 0x5c, 0x7a, 0x63, 0xa9, 0xcd, 0xea, 0x94, 0xc4, 0xfe, 0x35, 0x00,
	0x46, 0x28, 0x29, 0xa8, 0x53, 0x4d, 0x6d, 0xf8, 0x47, 0x8b, 0x0d, 0xff, 0x81, 0xc6, 0xee, 0x17,
	0xfb, 0xdd, 0x3c, 0x01, 0xd2, 0x62, 0xff, 0xef, 0x40, 0x27, 0x15, 0x79, 0x53, 0x3a, 0x58, 0xb5,
	0x9d, 0x0a, 0xd3, 0x90, 0x1d, 0xe8, 0xf0, 0xc2, 0x09, 0xda, 0xc9, 0x73, 0xe7, 0x1d, 0xc0, 0xee,
	0xb9, 0xc9, 0xf8, 0x27, 0xe6, 0x49, 0x81, 0xca, 0xad, 0x3b, 0x5d, 0x85, 0xbd, 0xd6, 0xd0, 0xf6,
	0xb7, 0xd0, 0xaf, 0x56, 0x2e, 0xbf, 0x10, 0x3a, 0xfa, 0x85, 0xf0, 0xa0, 0xfc, 0x42, 0xa8, 0x5c,
	0x28, 0x45, 0x68, 0xf9, 0xd9, 0x70, 0x17, 0x7a, 0x23, 0xbc, 0xae, 0xf2, 0x8b, 0x72, 0x0b, 0x1a,
	0x9c, 0x4d, 0x58, 0x7e, 0x4e, 0x6a, 0xc3, 0xbe, 0x03, 0xbd, 0xd7, 0x3c, 0x98, 0x04, 0x71, 0x4e,
	0x1b, 0xc0, 0x2a, 0x15, 0xf9, 0xb5, 0xaf, 0x3e, 0x0f, 0x7e, 0x6d, 0x42, 0xfb, 0xf0, 0xf8, 0xf4,
	0x8d, 0xaa, 0xa5, 0xae, 0xdb, 0x63, 0x26, 0xf5, 0x83, 0x92, 0x94, 0x8e, 0x67, 0x7c, 0x6c, 0x6e,
	0x97, 0x2e, 0xaa, 0xa5, 0x37, 0xe7, 0x53, 0x68, 0x1f, 0x33, 0xa9, 0x1f, 0x65, 0xef, 0x85, 0xdd,
	0xb8, 0xe4, 0x45, 0x46, 0x9e, 0x41, 0xff, 0x98, 0xc9, 0xd2, 0x42, 0xbd, 0x1f, 0x7b, 0xeb, 0xa3,
	0x0b, 0x4a, 0x46, 0x58, 0xd7, 0x5c, 0xf4, 0xcb, 0xb7, 0x89, 0x9e, 0x72, 0x39, 0xc5, 0x87, 0xee,
	0xb8, 0xcf, 0x71, 0xca, 0xfa, 0xa6, 0xba, 0x34, 0x87, 0xb5, 0x84, 0x2f, 0x46, 0xf0, 0x15, 0x6c,
	0x1e, 0x33, 0x99, 0xdf, 0x45, 0x87, 0x73, 0xdd, 0x6e, 0x52, 0x9a, 0x73, 0x65, 0x01, 0xb6, 0xb7,
	0x97, 0xaf, 0xa4, 0x52, 0xae, 0x2f, 0x60, 0xa3, 0x18, 0xca, 0xd5, 0x99, 0x2e, 0x1f, 0xd3, 0x97,
	0x4b, 0x63, 0xd2, 0x4a, 0x29, 0x67, 0xaa, 0x68, 0xe7, 0x23, 0x99, 0x5e, 0xc1, 0xf5, 0x4a, 0xa6,
	0xc5, 0x43, 0x72, 0xfb, 0x43, 0x2f, 0x9e, 0x2b, 0xf3, 0xfd, 0x00, 0x3b, 0x95, 0x7c, 0x4b, 0xaf,
	0xd3, 0xdb, 0x97, 0xbe, 0x84, 0xae, 0xcc, 0x7c, 0x02, 0xe4, 0x98, 0xc9, 0x93, 0x78, 0x46, 0xc3,
	0xc0, 0xcf, 0x0b, 0x7c, 0xd2, 0x32, 0x1c, 0x3e, 0xf8, 0xf1, 0xfe, 0x24, 0x90, 0xd3, 0x6c, 0xbc,
	0xef, 0x25, 0xd1, 0xe3, 0x88, 0x85, 0x61, 0x72, 0xe1, 0xf3, 0xe0, 0x5c, 0x32, 0x5e, 0xfc, 0x23,
	0x7b, 0x8c, 0xff, 0xc8, 0xc6, 0x4d, 0xfc, 0xf9, 0xf7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4d,
	0x23, 0x3a, 0x86, 0xb0, 0x0d, 0x00, 0x00,
}
