---
name: test
on:
  push:
    branches:
      - "*"
      - "!releases/**"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13.x

      - name: get deps
        run: go get -d -t ./...

      - name: test
        run: go test ./...
